// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogkcfyjwczaermhhtbmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9na2NmeWp3Y3phZXJtaGh0Ym1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTUzNDQsImV4cCI6MjA3Mzc5MTM0NH0.kkFpXGBuXt0QsfQcweeafoHcBtAM5jtWp1aUvcXlUfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});